import Head from 'next/head'
import Hero from '../components/Hero'
// import Slider from '../components/Slider'
import { SliderData } from '../components/Slider'

export default function Home() {
  return (
    console.log("This resume belongs to Junior Chang. Thank you for visiting and I look forward to meeting you."),
    <div>
      <Head>
        <title>Junior Chang, Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type='image/png' href="/favicon11.jpg" />
      </Head>

      <Hero heading="Junior Chang, Web Developer" message="I bring your ideas to live on the internet" />
      <Slider slides={SliderData} />

    </div>
  )
}
